{{- range $i, $ds := .Values.datasets }}
{{- if and $ds.enabled (and (not $ds.envFromConfigMap) $ds.env) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zyra.configmapName" (list $ $ds) }}
  labels:
    {{- include "zyra.labels" $ | nindent 4 }}
data:
{{- range $k, $v := $ds.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
---
{{- end }}
{{- end }}

